import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { Card, PageHeader } from "@/components/ui";
import { getDictionary } from "@/lib/i18n/locale";
import { EditTransactionForm } from "./edit-transaction-form";

export default async function EditCashTransactionPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const session = await auth();
  if (session?.user.role !== "ADMIN") redirect("/");
  const { t } = await getDictionary();
  const c = t.cashflow;

  const { id } = await params;
  const txn = await prisma.cashTransaction.findUnique({
    where: { id },
    include: {
      invoice: true,
      purchase: { include: { item: true } },
      healthRecord: { include: { flock: true } },
      capexItem: true,
    },
  });
  if (!txn) notFound();

  const source = txn.invoice
    ? { label: `${c.invoiceLabel} ${txn.invoice.invoiceNumber}`, href: `/invoices/${txn.invoice.id}` }
    : txn.purchase
      ? { label: `${c.purchaseOf} ${txn.purchase.item.name}`, href: `/inventory/purchases/${txn.purchase.id}` }
      : txn.healthRecord
        ? { label: `${c.healthRecordFor} "${txn.healthRecord.flock.name}"`, href: `/health/${txn.healthRecord.id}` }
        : txn.capexItem
          ? { label: `${c.capexItemLabel} "${txn.capexItem.name}"`, href: `/capex/${txn.capexItem.id}` }
          : null;

  return (
    <div>
      <PageHeader title={c.editTitle} />
      <Card>
        {source ? (
          <p className="text-sm text-stone-600 dark:text-stone-300">
            {c.autoGeneratedFrom}{" "}
            <Link href={source.href} className="text-emerald-700 hover:underline dark:text-emerald-400">
              {source.label}
            </Link>
            . {c.editThereInstead}
          </p>
        ) : (
          <EditTransactionForm txn={txn} />
        )}
      </Card>
    </div>
  );
}
